// Classic service worker (HB-3a). Generated by scripts/build-push-sw.mjs.
// No import: iOS 16.4–18.3 home-screen workers cannot load a module worker.
// Caches only the offline page and icons. App code and API responses stay
// network-only (assets are served no-store).
// Lock-screen text for a human push. The default is a count. A message body
// on the payload is ignored. A short server-set title (the declarative
// notification title, or payload.title) may replace the count title. It is
// a label such as "Codex needs your approval", not the message.

const ACTION_TITLES = { approve: "Approve", reject: "Reject", reply: "Reply" };

function countTitle(mention, dm, waiting) {
  if (dm > 0 && mention === 0) return waiting === 1 ? "Direct message" : "Direct messages";
  if (mention > 0 && dm === 0) return waiting === 1 ? "Mention" : "Mentions";
  return "Mentions and DMs";
}

function countBody(waiting) {
  if (waiting === 0) return "Something is waiting in the room";
  if (waiting === 1) return "1 waiting in the room";
  return `${waiting} waiting in the room`;
}

function shortLabel(value) {
  if (typeof value !== "string") return null;
  const text = value.replace(/[\r\n\u0000-\u001f\u007f]/g, " ").trim();
  if (!text || text.length > 80) return null;
  return text;
}

function roomPath(value) {
  if (typeof value !== "string" || !value.startsWith("/") || value.startsWith("//") || value.length > 2048) return null;
  return value;
}

function notificationActions(payload) {
  const list = Array.isArray(payload?.actions) ? payload.actions : [];
  const seen = new Set();
  const actions = [];
  for (const item of list) {
    const action = item?.action;
    if (!Object.hasOwn(ACTION_TITLES, action) || seen.has(action)) continue;
    seen.add(action);
    actions.push({ action, title: ACTION_TITLES[action] });
    if (actions.length === 2) break;
  }
  return actions;
}

function needsMeCountFromPush(payload) {
  const value = payload?.needsMeCount ?? payload?.notification?.app_badge;
  return Number.isInteger(value) && value >= 0 && value <= 99 ? value : null;
}

// Rich (v2) rendering: a payload that carries the member's preview
// preference shows who wrote and the start of what they wrote. Anything
// else — v1 payloads, or v2 payloads where the member turned preview off —
// renders the counts, exactly as before. Content only reaches the lock
// screen when the server put it on the payload, which only happens with
// preview enabled for that member in that room.
function richTitle(payload, mention, dm, waiting) {
  if (payload?.v !== 2) return null;
  const name = shortLabel(payload?.sender?.name);
  if (!name || typeof payload?.preview !== "string" || !payload.preview) return null;
  return name;
}

function richBody(payload, mention, dm, waiting) {
  if (payload?.v !== 2) return null;
  const name = shortLabel(payload?.sender?.name);
  if (!name || typeof payload?.preview !== "string" || !payload.preview) return null;
  const text = payload.preview.replace(/[\r\n\x00-\u001f\x7f]/g, " ").trim();
  if (!text) return null;
  return text.length > 140 ? text.slice(0, 140) : text;
}

function notificationFromPush(payload) {
  const counts = payload && typeof payload === "object" ? payload.counts : null;
  const mention = Number.isInteger(counts?.mention) && counts.mention > 0 ? counts.mention : 0;
  const dm = Number.isInteger(counts?.dm) && counts.dm > 0 ? counts.dm : 0;
  const waiting = mention + dm;
  const roomId = typeof payload?.roomId === "string" && payload.roomId ? payload.roomId : null;
  const url = roomPath(payload?.data?.url) || roomPath(payload?.notification?.navigate_url) || roomPath(payload?.url)
    || (roomId ? `/?room=${encodeURIComponent(roomId)}` : "/");
  const title = shortLabel(payload?.notification?.title) || shortLabel(payload?.title)
    || richTitle(payload, mention, dm, waiting) || countTitle(mention, dm, waiting);
  const body = richBody(payload, mention, dm, waiting) ?? countBody(waiting);
  return {
    title,
    body,
    tag: roomId ? `room:${roomId}` : "room",
    data: { roomId, url },
    actions: notificationActions(payload),
    needsMeCount: needsMeCountFromPush(payload)
  };
}

const CACHE_NAME = "room-pwa-v1";
const CACHE_ALLOW = [
  "/offline.html",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/maskable-512.png",
  "/icons/apple-touch-icon-180.png"
];

self.addEventListener("install", event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await cache.addAll(CACHE_ALLOW);
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(key => key !== CACHE_NAME).map(key => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", event => {
  if (event.request.mode === "navigate") {
    event.respondWith((async () => {
      try {
        return await fetch(event.request);
      } catch {
        const cache = await caches.open(CACHE_NAME);
        const offline = await cache.match("/offline.html");
        return offline || new Response("Room is offline.", { status: 503, headers: { "Content-Type": "text/plain; charset=utf-8" } });
      }
    })());
    return;
  }
  // The offline page's own icon: network first, cached copy when the network
  // fails, so the no-network page keeps its mark. Everything else stays
  // network-only (assets are served no-store).
  const path = new URL(event.request.url).pathname;
  if (CACHE_ALLOW.includes(path)) {
    event.respondWith((async () => {
      try {
        return await fetch(event.request);
      } catch (error) {
        const cache = await caches.open(CACHE_NAME);
        const cached = await cache.match(path);
        if (cached) return cached;
        throw error;
      }
    })());
    return;
  }
  event.respondWith(fetch(event.request));
});

self.addEventListener("push", event => {
  let payload = {};
  try { payload = event.data && event.data.json ? event.data.json() : {}; } catch { payload = {}; }
  const note = notificationFromPush(payload);
  const options = { body: note.body, tag: note.tag, renotify: false, data: note.data };
  const actionsSupported = typeof Notification === "function" && "actions" in Notification.prototype;
  if (actionsSupported && note.actions.length) options.actions = note.actions;
  const badge = note.needsMeCount;
  event.waitUntil(Promise.all([
    self.registration.showNotification(note.title, options),
    (async () => {
      if (badge === null) return;
      if (badge === 0 && navigator.clearAppBadge) await navigator.clearAppBadge();
      else if (badge > 0 && navigator.setAppBadge) await navigator.setAppBadge(badge);
    })()
  ]));
});

self.addEventListener("notificationclick", event => {
  event.notification.close();
  const data = event.notification.data || {};
  const target = typeof data.url === "string" && data.url ? data.url : new URL(self.registration.scope).href;
  // Approve, reject, and reply are HB-3b. Until that decide path exists, an
  // action click opens the same item a plain click opens.
  event.waitUntil((async () => {
    const windows = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
    const scope = new URL(self.registration.scope);
    for (const client of windows) {
      let origin = "";
      try { origin = new URL(client.url).origin; } catch { origin = ""; }
      if (origin !== scope.origin) continue;
      if (client.focus) await client.focus();
      if (client.navigate) await client.navigate(target);
      return;
    }
    await self.clients.openWindow(target);
  })());
});
