// Brand assets (docs/DESIGN.md): one mark, generated by
// scripts/build-brand-assets.mjs, used on every surface.
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { PUBLIC_NOT_FOUND_HTML, PUBLIC_SEARCH_CSP } from "../deploy/public-search.mjs";

const read = path => readFileSync(new URL(`../${path}`, import.meta.url));
const pngSize = path => { const b = read(path); assert.equal(b.toString("ascii", 1, 4), "PNG", path); return [b.readUInt32BE(16), b.readUInt32BE(20)]; };

test("favicon and icon are the green cube on black, not a text tile", async () => {
  const { iconSvg } = await import("../scripts/build-desktop-icon.mjs");
  for (const file of ["favicon.svg", "icon.svg"]) {
    const svg = read(file).toString();
    assert.doesNotMatch(svg, /<text/, `${file} must not depend on a font`);
    assert.match(svg, /aria-label="Project Room"/);
    assert.match(svg, /stroke="#3dff8b"/, `${file} draws the green cube`);
    assert.match(svg, /stop-color="#000000"/, `${file} sits on black`);
    assert.equal(svg, iconSvg("small", { mode: "square" }), `${file} is the small drawing, the one made for tab size`);
  }
  assert.equal(read("favicon.svg").toString(), read("icon.svg").toString());
  const mono = read("brand/mark-mono.svg").toString();
  assert.match(mono, /currentColor/);
  assert.doesNotMatch(mono, /#[0-9a-f]{3,6}"/i, "the one-colour mark has no fixed colours");
});

test("every manifest icon exists at its declared size", () => {
  const manifest = JSON.parse(read("manifest.webmanifest"));
  for (const icon of manifest.icons.filter(i => i.type === "image/png")) {
    const [w, h] = pngSize(icon.src.slice(1));
    assert.equal(`${w}x${h}`, icon.sizes, icon.src);
  }
  assert.deepEqual(pngSize("icons/apple-touch-icon-180.png"), [180, 180]);
});

test("static share images are 1200x630", () => {
  for (const name of ["home", "about", "offers", "compare", "receipts"]) assert.deepEqual(pngSize(`og/${name}.png`), [1200, 630], name);
});

test("the app top bar shows the mark and sign-in keeps the wordmark", () => {
  const html = read("index.html").toString();
  assert.match(html, /<img class="brand-mark" src="\/favicon.svg" alt="" width="32" height="32">/);
  assert.match(html, /<h1 id="auth-title" tabindex="-1">PROJECT ROOM<\/h1>/);
});

test("the 404 page is styled and its policy allows its inline stylesheet", () => {
  assert.match(PUBLIC_NOT_FOUND_HTML, /<style>/);
  assert.match(PUBLIC_NOT_FOUND_HTML, /<img src="\/favicon.svg" alt=""/);
  assert.match(PUBLIC_SEARCH_CSP, /style-src 'unsafe-inline'/);
  assert.match(PUBLIC_SEARCH_CSP, /img-src 'self'/);
  assert.equal(read("404.html").toString(), PUBLIC_NOT_FOUND_HTML);
});
