import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { candidateRuntimeFixture } from '../scripts/candidate-runtime-fixture.mjs';
import { createRuntimePackage, verifyRuntimePackage } from '../scripts/runtime-package.mjs';

test('Gmail package includes callback and validates pinned dependency beyond file hashes', t => {
  const directory = mkdtempSync(join(tmpdir(), 'gmail-package-'));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  const candidate = candidateRuntimeFixture(fileURLToPath(new URL('../', import.meta.url)), directory);
  const destination = join(directory, 'runtime'); createRuntimePackage({ ...candidate, destination });
  const manifestPath = join(destination, 'runtime-manifest.json');
  const manifest = JSON.parse(readFileSync(manifestPath));
  assert.ok(manifest.publicAssets.includes('src/gmail-callback.js'));
  assert.equal(manifest.dependencies[0].name, 'postal-mime');
  assert.equal(manifest.dependencies[0].version, '3.0.0');
  assert.match(manifest.dependencyInstallation, /Required separately/);
  assert.ok(manifest.files.some(file => file.path === 'server/gmail-runtime.mjs'));
  const lockPath = join(destination, 'package-lock.json');
  const lock = JSON.parse(readFileSync(lockPath));
  lock.packages['node_modules/postal-mime'].integrity = 'sha512-tampered';
  const bytes = Buffer.from(JSON.stringify(lock)); writeFileSync(lockPath, bytes);
  const entry = manifest.files.find(file => file.path === 'package-lock.json');
  entry.bytes = bytes.length; entry.sha256 = createHash('sha256').update(bytes).digest('hex');
  writeFileSync(manifestPath, JSON.stringify(manifest));
  assert.throws(() => verifyRuntimePackage(destination));
});
