// Doc-accuracy regression guard for the two audited MCP docs:
//   docs/history/MCP-INSTALL.md
//   docs/history/mcp-receipt-binding.md
//
// Authoring-gate answers (see .agents/skills/test-audit/SKILL.md):
// 1. Contract: the documented installer surface (client names, flags, the
//    removal of the one-line curl|sh flow) matches the implementation; the
//    route wiring stays unmounted; backtick path references inside the
//    audited docs resolve to committed files.
// 2. Credible regression: a lane changes parseArgs targets/flags, mounts
//    /room/install, restores the deleted bootstrapper generator, or rewrites
//    a doc sentence, and the doc silently drifts (this file was created after
//    exactly that drift was found: the "Code/Codex CLI" miswording, the
//    stale server/mcp-install-script.mjs reference post-#1321, and a broken
//    docs/RECEIPTS-PAGE.md path in docs/history/).
// 3. Existing coverage does not catch it: tests/docs-relative-links.test.js
//    scans only top-level docs/*.md Markdown links — not inline-code path
//    references, not docs/history/*.md — and no test asserts the audited
//    docs' claims against the installer's actual behavior.
// 4. No production seam: only the existing parseArgs export plus file reads.

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parseArgs } from "../scripts/room-mcp-init.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const history = join(root, "docs", "history");
const installDoc = readFileSync(join(history, "MCP-INSTALL.md"), "utf8");
const bindingDoc = readFileSync(join(history, "mcp-receipt-binding.md"), "utf8");
const initSrc = readFileSync(join(root, "scripts", "room-mcp-init.mjs"), "utf8");
const httpSrc = readFileSync(join(root, "server", "http.mjs"), "utf8");

const CLIENT_ALIASES = {
  claude: "claude",
  cursor: "cursor",
  codex: "codex",
  antigravity: "antigravity",
  "vs code": "vscode",
  copilot: "copilot",
};

function documentedClients() {
  const segment = /auto-detects installed clients — (.*?) — and registers/s.exec(installDoc);
  assert.ok(segment, "install doc: detection sentence missing");
  return segment[1]
    .replace(/\([^)]*\)/g, "")
    .split(/,|;/)
    .map((part) => part.trim().toLowerCase())
    .map((part) => CLIENT_ALIASES[part])
    .filter(Boolean);
}

test("install doc: every documented client is accepted by the init script", () => {
  const names = documentedClients();
  assert.equal(names.length, 6, `expected 6 documented clients, got: ${names.join(", ")}`);
  for (const name of names) {
    assert.doesNotThrow(() => parseArgs([name]), `documented client "${name}" rejected by parseArgs`);
  }
});

test("install doc: documented flags are accepted by the init script", () => {
  const args = parseArgs(["cursor", "codex", "--dry-run"]);
  assert.deepEqual(args.targets, ["cursor", "codex"]);
  assert.equal(args.dryRun, true);
});

test("install doc: Claude entry attributes the claude CLI, not the codex CLI", () => {
  const claudeEntry = /Claude\s*\(([^)]*)\)/.exec(installDoc);
  assert.ok(claudeEntry, "install doc: Claude parenthetical missing");
  // installClaude tries ["claude", "mcp", "add", ...] first — the doc must
  // name that CLI, not the Codex CLI (historical miswording: "Code/Codex CLI").
  assert.ok(initSrc.includes('["claude", "mcp", "add"'), "installer must try the claude CLI first");
  assert.ok(/claude/i.test(claudeEntry[1]), `Claude entry must name the claude CLI: ${claudeEntry[1]}`);
  assert.ok(!/codex/i.test(claudeEntry[1]), `Claude entry must not mention the Codex CLI: ${claudeEntry[1]}`);
});

test("install doc: records the #1321 removal of the one-line curl|sh flow", () => {
  assert.ok(installDoc.includes("#1321"), "install doc must record the #1321 removal");
  // The bootstrapper generator was deleted as unreachable; the doc must not
  // describe it as the current mechanism.
  assert.ok(!existsSync(join(root, "server", "mcp-install-script.mjs")), "server/mcp-install-script.mjs is back — update the doc");
  assert.ok(!/generated by\s*\n?\s*`?server\/mcp-install-script\.mjs`?\s*\)?\s*\./i.test(installDoc),
    "install doc still presents the deleted bootstrapper generator as current");
});

test("install doc: /room/install route still unmounted", () => {
  // When a lane mounts the route (and re-adds the generator), this fails so
  // the doc is updated instead of drifting.
  assert.ok(!httpSrc.includes("/room/install"), "/room/install is now mounted — update the doc");
  assert.ok(!httpSrc.includes("mcp-install-script"), "http.mjs now references the installer — update the doc");
});

test("install doc: surviving example command parses in the init script", () => {
  const m = /node scripts\/room-mcp-init\.mjs ([^\n`]*)/.exec(installDoc);
  assert.ok(m, "install doc: no direct init-script example found");
  assert.doesNotThrow(() => parseArgs(m[1].trim().split(/\s+/).filter(Boolean)));
});

test("binding doc: backtick path references resolve to committed files", () => {
  const refs = [...bindingDoc.matchAll(/`([A-Za-z0-9_.\/-]+\.md)`/g)].map((m) => m[1]);
  assert.ok(refs.length > 0, "binding doc: no .md path references found");
  for (const ref of refs) {
    assert.ok(
      existsSync(resolve(history, ref)),
      `binding doc: broken path reference "${ref}" (resolved against docs/history/)`
    );
  }
});
