import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  MCP_INSTALL_PATH,
  MCP_INIT_PATH,
  mcpInstallScript,
  mcpInstallScriptResponse,
} from "../server/mcp-install-script.mjs";

const HOST = "https://www.getdasha.com";

test("generated installer is a valid posix script advertising the one-liner", t => {
  const script = mcpInstallScript({ host: HOST });
  assert.match(script, /^#!\/bin\/sh\n/);
  assert.match(script, new RegExp(`curl -fsSL ${HOST.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}${MCP_INSTALL_PATH} \\| sh`));
  assert.ok(script.includes(`INIT_URL='${HOST}${MCP_INIT_PATH}'`));
  assert.match(script, /command -v node/);
  assert.match(script, /node -p "process\.versions\.node/);
  assert.match(script, /\$NODE_MAJOR.*" -lt 18/);
  // Hosted-MCP fallback: no Node still leaves the user with working snippets.
  assert.match(script, /claude mcp add --transport http --scope user project-room/);
  assert.match(script, /codex mcp add project-room --url/);
  assert.match(script, /"\$TMP_INIT" "\$@"/);
  // The real boundary: the generated bytes must parse as shell.
  const dir = mkdtempSync(join(tmpdir(), "room-install-sh-"));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  const path = join(dir, "install.sh");
  writeFileSync(path, script);
  const res = spawnSync("sh", ["-n", path]);
  assert.equal(res.status, 0, String(res.stderr));
});

test("host is normalized and unsafe values are rejected", () => {
  const script = mcpInstallScript({ host: `${HOST}/` });
  assert.ok(script.includes(`INIT_URL='${HOST}${MCP_INIT_PATH}'`));
  assert.throws(() => mcpInstallScript({ host: "https://x.example/'; evil; '" }), /unsafe value/);
});

test("route helper serves the script on GET, headers only on HEAD, 405 otherwise", () => {
  const get = mcpInstallScriptResponse({ host: HOST, method: "GET" });
  assert.equal(get.status, 200);
  assert.equal(get.headers["content-type"], "text/x-shellscript; charset=utf-8");
  assert.equal(get.headers["content-length"], String(Buffer.byteLength(get.body)));
  assert.ok(get.body.startsWith("#!/bin/sh"));

  const head = mcpInstallScriptResponse({ host: HOST, method: "HEAD" });
  assert.equal(head.status, 200);
  assert.equal(head.body, "");
  assert.equal(head.headers["content-length"], get.headers["content-length"]);

  const post = mcpInstallScriptResponse({ host: HOST, method: "POST" });
  assert.equal(post.status, 405);
  assert.equal(post.headers.allow, "GET, HEAD");
});
