import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { RoomStore } from "../server/store.mjs";
import { AgentRooms } from "../server/agent-rooms.mjs";
import { createRoomServer } from "../server/http.mjs";
import { saveAgentConnection } from "../client/agent-connection.mjs";
import { openMcpTestClient } from "../scripts/mcp-test-client.mjs";

test("hosted and bound stdio selected-work hints and briefs expose callable participant reply pointers", async t => {
  const directory = mkdtempSync(join(tmpdir(), "room-work-replies-")), store = new RoomStore(join(directory, "room.sqlite"));
  const identity = store.identities.create("Owner");
  new AgentRooms(store).create(identity.secret, { roomId: "test-room", title: "Test", purpose: "Selected replies", kind: "personal", displayName: "Owner" });
  const server = createRoomServer({ store }); await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
  const origin = `http://127.0.0.1:${server.address().port}`, config = join(directory, "agent");
  let stdio;
  t.after(async () => { if (stdio) await stdio.close(); server.closeStreams(); server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); store.close(); rmSync(directory, { recursive: true, force: true }); });
  const send = (type, data) => store.command(identity.secret, "test-room", { id: crypto.randomUUID(), type, data });
  send("member.added", { memberId: "peer", displayName: "Peer", kind: "human", permissions: [] });
  send("work.proposed", { workItemId: "task", title: "Task", definitionOfDone: "Read reply", mode: "read", accountableMemberId: identity.identityId });
  store.dmConsents.request("test-room", identity.identityId, "peer", "testing"); store.dmConsents.decide("test-room", "peer", identity.identityId, "approve");
  send("message.posted", { messageId: "pending", body: "PRIVATE-BODY-SENTINEL", toMemberId: "peer", requestKind: "reply", workItemId: "task" });
  const call = async (name, args) => (await (await fetch(`${origin}/room/mcp?profile=full`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${identity.secret}` }, body: JSON.stringify({ jsonrpc: "2.0", id: "test", method: "tools/call", params: { name, arguments: args } }) })).json()).result;
  for (let i = 0; i < 25; i++) send("message.posted", { messageId: `pending-extra-${i}`, body: "PRIVATE-BODY-SENTINEL", toMemberId: "peer", requestKind: "reply", workItemId: "task" });
  const before = store.room("test-room").sequence;
  const hosted = (await call("room_read_work", { roomId: "test-room", workItemId: "task" })).structuredContent;
  assert.equal(hosted.replyRequestContext.truncated, true);
  assert.deepEqual(hosted.replyRequestContext.nextRead.arguments, { roomId: "test-room", direction: "both", status: "open" });
  assert.equal((await call(hosted.replyRequestContext.nextRead.tool, hosted.replyRequestContext.nextRead.arguments)).structuredContent.requests.length, 26);
  const pointer = hosted.replyRequestContext.requests.find(q => q.id === "pending").nextRead;
  assert.deepEqual(pointer, { tool: "room_read_request", arguments: { roomId: "test-room", requestMessageId: "pending" } });
  assert.equal((await call(pointer.tool, pointer.arguments)).structuredContent.selection.requestMessageId, "pending");
  const brief = (await call("room_read_work", { roomId: "test-room", workItemId: "task", brief: true })).structuredContent.brief;
  assert.match(brief, /Pending linked reply requests: 26/); assert.match(brief, /pending/); assert.match(brief, /room_read_request/);
  assert.equal(brief.includes("PRIVATE-BODY-SENTINEL"), false);
  saveAgentConnection(config, { version: 1, origin, roomId: "test-room", memberId: identity.identityId, token: identity.secret });
  stdio = await openMcpTestClient(config);
  const bound = (await stdio.call("room_read_work", { workItemId: "task" })).result.structuredContent;
  assert.deepEqual(bound.replyRequestContext.requests.find(q => q.id === "pending").nextRead.arguments, { requestMessageId: "pending" });
  assert.equal((await stdio.call("room_read_request", bound.replyRequestContext.requests.find(q => q.id === "pending").nextRead.arguments)).result.structuredContent.selection.requestMessageId, "pending");
  const boundBrief = (await stdio.call("room_read_work", { workItemId: "task", brief: true })).result.structuredContent.brief;
  assert.match(boundBrief, /Pending linked reply requests: 26/); assert.match(boundBrief, /pending/);
  assert.equal(boundBrief.includes("PRIVATE-BODY-SENTINEL"), false);
  assert.equal(store.room("test-room").sequence, before);
});
