// Replay-safe persisted-row serialization (RC-2026-09-27-2730).
//
// Contract: rows written by older code must load under new code. The fixtures
// below are hand-written OLD-format JSON (plain objects with no envelope, as
// the pre-change code wrote them) — never generated by the codec under test.
// Each test asserts one property: unknown fields dropped, missing fields
// defaulted, moved kind tags resolved, new-format round trips.

import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  encodeRow, decodeRow, resolveKind, ROW_FORMAT_V, MOVED_KINDS,
} from "../server/persisted-row.mjs";
import { createDurableWorkClaimRegistry, workClaimSchema, WORK_CLAIM_ROW_KIND } from "../server/work-claim-sqlite.mjs";
import { DispatchJournal, DISPATCH_JOURNAL_ROW_KIND } from "../server/dispatch-journal.mjs";
import { BountyEscrow, bountyEscrowSchema, BOUNTY_DISPUTE_ROW_KIND } from "../server/bounty-escrow.mjs";

// --- codec unit tests -------------------------------------------------------

test("encodeRow wraps data in a version-tagged envelope without mutating the input", () => {
  const data = { id: "a", state: "claimed" };
  const row = encodeRow("work-claim", data);
  assert.equal(row.v, ROW_FORMAT_V);
  assert.equal(row.kind, "work-claim");
  assert.deepEqual(row.data, data);
  assert.notEqual(row.data, data);
  assert.deepEqual(data, { id: "a", state: "claimed" });
});

test("encodeRow rejects a missing kind and non-object data", () => {
  assert.throws(() => encodeRow("", { a: 1 }), /kind is required/);
  assert.throws(() => encodeRow("k", null), /data must be an object/);
  assert.throws(() => encodeRow("k", [1]), /data must be an object/);
});

test("decodeRow round-trips a new envelope and ignores unknown envelope fields", () => {
  const stored = JSON.stringify({ ...encodeRow("work-claim", { id: "a", state: "claimed" }), envelopeJunk: "ignored" });
  const out = decodeRow(stored, { kind: "work-claim", fields: ["id", "state"], defaults: { owner: null } });
  assert.deepEqual(out, { id: "a", state: "claimed", owner: null });
});

test("decodeRow loads a legacy row: unknown fields dropped, missing fields defaulted", () => {
  // Hand-written OLD format: what the pre-change code persisted (bare
  // JSON.stringify of the record, no envelope). `retired` is a field the new
  // code no longer knows; `blobs` was added after this row was written.
  const legacy = JSON.stringify({ id: "old-1", title: "Old", state: "claimed", owner: "jill", retired: "gone" });
  const out = decodeRow(legacy, {
    kind: "work-claim",
    fields: ["id", "title", "state", "owner", "blobs"],
    defaults: { title: null, state: "unclaimed", owner: null, blobs: [] },
  });
  assert.deepEqual(out, { id: "old-1", title: "Old", state: "claimed", owner: "jill", blobs: [] });
  assert.ok(!("retired" in out), "unknown field must be dropped");
});

test("decodeRow drops unknown data fields on enveloped rows and defaults the missing", () => {
  const stored = JSON.stringify({ v: 1, kind: "work-claim",
    data: { id: "a", state: "claimed", futureField: "drop me" } });
  const out = decodeRow(stored, { kind: "work-claim", fields: ["id", "state"], defaults: { owner: null } });
  assert.deepEqual(out, { id: "a", state: "claimed", owner: null });
});

test("decodeRow resolves a moved kind tag through the move map", () => {
  // The row was written before the journal module was renamed; the recorded
  // kind no longer exists under that name.
  const stored = JSON.stringify({ v: 1, kind: "dispatch-log", data: { key: "k", state: "intended" } });
  const out = decodeRow(stored, {
    kind: "dispatch-journal",
    fields: ["key", "state"],
    moved: { "dispatch-log": "dispatch-journal" },
  });
  assert.deepEqual(out, { key: "k", state: "intended" });
  assert.equal(resolveKind("dispatch-log", { "dispatch-log": "dispatch-journal" }), "dispatch-journal");
  assert.equal(resolveKind("dispatch-journal"), "dispatch-journal");
  assert.deepEqual(MOVED_KINDS, {}, "the shipped move map starts empty and append-only");
});

test("decodeRow throws on kind mismatch: misrouted data is corruption, not an old row", () => {
  const stored = JSON.stringify(encodeRow("bounty-dispute", { disputeId: "d1" }));
  assert.throws(() => decodeRow(stored, { kind: "work-claim", fields: ["disputeId"] }), /kind mismatch/);
});

test("a legacy body carrying its own kind field is not misread as an envelope", () => {
  // Regression guard: legacy dispute bodies have kind "economic" /
  // "coordination" — envelope detection must key on `v`, never on `kind`.
  const legacy = JSON.stringify({ disputeId: "d1", kind: "economic", state: "opened" });
  const out = decodeRow(legacy, { kind: "bounty-dispute", fields: ["disputeId", "kind", "state", "notified"], defaults: { notified: false } });
  assert.deepEqual(out, { disputeId: "d1", kind: "economic", state: "opened", notified: false });
});

test("decodeRow still throws on corrupt rows and accepts parsed objects", () => {
  assert.throws(() => decodeRow("[1,2]", { fields: [] }), /not an object/);
  assert.throws(() => decodeRow("null", { fields: [] }), /not an object/);
  assert.throws(() => decodeRow("{oops", { fields: [] }), SyntaxError);
  assert.deepEqual(decodeRow({ id: "a" }, { fields: ["id"] }), { id: "a" });
});

// --- claims surface: server/work-claim-sqlite.mjs ----------------------------

const workClaimDb = t => {
  const db = new DatabaseSync(":memory:");
  db.exec(workClaimSchema);
  t.after(() => db.close());
  return db;
};

test("work-claim registry: legacy row loads with unknown fields dropped and missing defaulted", t => {
  // Hand-written OLD format: a row persisted by the pre-envelope code
  // (JSON.stringify(item) straight into item_json), written before the
  // `blobs` / `reviewedBy` fields existed, carrying a retired field.
  const legacyItem = JSON.stringify({ id: "old-1", title: "Old work", state: "claimed",
    owner: "jill", history: [], claimedAt: "2026-01-01T00:00:00.000Z",
    leaseStartAt: "2026-01-01T00:00:00.000Z", leaseExpiresAt: "2026-01-01T06:00:00.000Z",
    retiredField: "drop me" });
  const db = workClaimDb(t);
  db.prepare("INSERT INTO work_claims (room_id, claim_id, item_json, updated_at) VALUES (?,?,?,?)")
    .run("room1", "old-1", legacyItem, 1);
  const registry = createDurableWorkClaimRegistry(db);
  const item = registry.get("room1", "old-1");
  assert.equal(item.id, "old-1");
  assert.equal(item.title, "Old work");
  assert.equal(item.state, "claimed");
  assert.equal(item.owner, "jill");
  assert.deepEqual(item.blobs, [], "missing field takes the current default");
  assert.equal(item.reviewedBy, null, "missing field takes the current default");
  assert.ok(!("retiredField" in item), "unknown field is dropped");
});

test("work-claim registry: new writes carry the version envelope and round-trip", t => {
  const db = workClaimDb(t);
  const registry = createDurableWorkClaimRegistry(db);
  registry.set("room1", { id: "new-1", title: "New", state: "unclaimed", owner: null });
  const raw = JSON.parse(db.prepare("SELECT item_json FROM work_claims WHERE claim_id=?").get("new-1").item_json);
  assert.equal(raw.v, ROW_FORMAT_V);
  assert.equal(raw.kind, WORK_CLAIM_ROW_KIND);
  assert.equal(raw.data.id, "new-1");
  const item = registry.get("room1", "new-1");
  assert.equal(item.id, "new-1");
  assert.equal(item.state, "unclaimed");
});

// --- journal surface: server/dispatch-journal.mjs ------------------------------

const journalDir = t => {
  const dir = mkdtempSync(join(process.env.TMPDIR ?? tmpdir(), "persisted-row-journal-"));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  return dir;
};

test("dispatch journal: legacy JSONL lines load under new code", t => {
  // Hand-written OLD format: lines as the pre-envelope code appended them
  // (JSON.stringify of the entry, no envelope), one carrying an unknown field.
  const path = join(journalDir(t), "dispatch.jsonl");
  writeFileSync(path, [
    JSON.stringify({ key: "k1", roomId: "r", workItemId: "w", payloadDigest: "d",
      state: "intended", at: "2026-01-01T00:00:00.000Z" }),
    JSON.stringify({ key: "k1", state: "dispatched", jobId: "job-1",
      at: "2026-01-01T00:01:00.000Z", mystery: "drop me" }),
  ].join("\n") + "\n");
  const journal = new DispatchJournal(path);
  const record = journal.get("k1");
  assert.equal(record.state, "dispatched");
  assert.equal(record.jobId, "job-1");
  assert.equal(record.payloadDigest, "d");
  assert.ok(!("mystery" in record), "unknown entry field is dropped on replay");
});

test("dispatch journal: new entries carry the version envelope and replay", t => {
  const path = join(journalDir(t), "dispatch.jsonl");
  const journal = new DispatchJournal(path);
  journal.intend({ key: "k2", roomId: "r", workItemId: "w", payload: { a: 1 } });
  journal.transition("k2", "done", { jobId: "job-2" });
  const lines = readFileSync(path, "utf8").trim().split("\n").map(l => JSON.parse(l));
  assert.equal(lines.length, 2);
  for (const line of lines) {
    assert.equal(line.v, ROW_FORMAT_V);
    assert.equal(line.kind, DISPATCH_JOURNAL_ROW_KIND);
  }
  assert.equal(lines[1].data.state, "done");
  const reopened = new DispatchJournal(path);
  assert.equal(reopened.get("k2").state, "done");
  assert.equal(reopened.get("k2").jobId, "job-2");
});

// --- receipts surface: bounty dispute records in server/bounty-escrow.mjs -----

const escrowOn = (t, db) => {
  const transaction = fn => fn();
  const store = { db, transaction, readTransaction: transaction };
  return new BountyEscrow(store, { now: () => 1_786_000_000_000, allowLegacyStringLanes: true });
};

const legacyDisputeBody = () => JSON.stringify({
  // Hand-written OLD format: what _persistDispute wrote pre-envelope
  // (JSON.stringify(dispute) straight into bounty_disputes.body), from before
  // the `notified` field existed, carrying an unknown field.
  disputeId: "dsp_old", bountyId: "b1", bountyAmount: 10000, kind: "economic",
  bondSnapshot: 500, maxDisputeCost: 250, state: "opened", tier: 0,
  raisedBy: "id:agent/jill", reason: "grounds", evidence: [], decider: null,
  escalations: [], recordedCost: 0, forfeitedBond: 0, resolution: null,
  unavailable: null, legacyNote: "drop me",
});

test("bounty dispute hydration: legacy body loads with unknown dropped and missing defaulted", t => {
  const db = new DatabaseSync(":memory:");
  t.after(() => db.close());
  db.exec(bountyEscrowSchema);
  db.prepare("INSERT INTO bounty_disputes (dispute_id, room_id, body, updated_at) VALUES (?,?,?,?)")
    .run("dsp_old", "room1", legacyDisputeBody(), "2026-01-01T00:00:00.000Z");
  const dispute = escrowOn(t, db).getDispute("room1", "dsp_old");
  assert.equal(dispute.disputeId, "dsp_old");
  assert.equal(dispute.state, "opened");
  assert.equal(dispute.kind, "economic");
  assert.equal(dispute.notified, false, "missing field takes the current default");
  assert.ok(!("legacyNote" in dispute), "unknown field is dropped");
});

test("bounty dispute hydration: new envelope rows read back through the real path", t => {
  const db = new DatabaseSync(":memory:");
  t.after(() => db.close());
  db.exec(bountyEscrowSchema);
  const record = { disputeId: "dsp_new", bountyId: "b1", bountyAmount: 10000, kind: "coordination",
    bondSnapshot: "none", maxDisputeCost: 0, state: "challenged", tier: 0,
    raisedBy: "id:agent/jill", reason: "grounds", evidence: [], decider: null,
    challengedBy: "id:agent/jill", escalations: [], recordedCost: 0, forfeitedBond: 0,
    resolution: null, unavailable: null, notified: true };
  db.prepare("INSERT INTO bounty_disputes (dispute_id, room_id, body, updated_at) VALUES (?,?,?,?)")
    .run("dsp_new", "room1", JSON.stringify(encodeRow(BOUNTY_DISPUTE_ROW_KIND, record)), "2026-01-01T00:00:00.000Z");
  const stored = JSON.parse(db.prepare("SELECT body FROM bounty_disputes WHERE dispute_id=?").get("dsp_new").body);
  assert.equal(stored.v, ROW_FORMAT_V);
  assert.equal(stored.kind, BOUNTY_DISPUTE_ROW_KIND);
  const dispute = escrowOn(t, db).getDispute("room1", "dsp_new");
  assert.equal(dispute.disputeId, "dsp_new");
  assert.equal(dispute.state, "challenged");
  assert.equal(dispute.notified, true);
});
