import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {rmSync} from 'node:fs';
import {createAcceptanceFixture} from '../scripts/acceptance-fixture.mjs';
import {createRoomServer} from '../server/http.mjs';
import {TelegramReceiveQueue} from '../server/telegram-receive-queue.mjs';
import {TelegramConnectionRegistry} from '../server/telegram-connection-registry.mjs';
import {MessagingReceiveGrants} from '../server/messaging-receive-grants.mjs';
import {createTelegramConnections} from '../server/telegram-connections.mjs';

test('Telegram consent is private, bounded, renewable, and stop prevents host polling',async t=>{
  const f=createAcceptanceFixture(),dbs=Array.from({length:3},()=>new DatabaseSync(':memory:'));
  const account=f.store.accountForMember('commons','owner'),slot=f.store.createAccountSessionSlot();
  const auth=f.store.loginAccountSession(slot.token,f.store.issueAccountAccessKey(account.id),0),session={token:slot.token,binding:auth.sessionBinding};
  const registry=new TelegramConnectionRegistry({db:dbs[0],key:Buffer.alloc(32,8)});
  const grants=new MessagingReceiveGrants({db:dbs[1],store:f.store});
  const queue=new TelegramReceiveQueue({db:dbs[2],key:Buffer.alloc(32,7),accountId:account.id,connectionId:'one',authEpoch:0});
  const config={accountId:account.id,connectionId:'one',authEpoch:0,expectedRevision:0,botId:'123456',token:'123456:abcdefghijklmnopqrstuvwxyz',chatIds:[44]};
  registry.configure(config);let polls=0;
  const options={store:f.store,registry,connections:[{accountId:account.id,connectionId:'one',queue}],fetchImpl:async()=>{
    polls++;return Response.json({ok:true,result:polls===1?[{update_id:9,message:{message_id:9,chat:{id:44},from:{id:44},date:1700000000,text:'Private test'}}]:[]});
  }};
  const service=createTelegramConnections({...options,receiveGrants:grants});
  assert.deepEqual(createTelegramConnections(options).receivingStatus(session),{enabled:false,connections:[]});
  const server=createRoomServer({store:f.store,telegramConnections:service});await new Promise(r=>server.listen(0,'127.0.0.1',r));
  t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));grants.close();registry.close();dbs.forEach(d=>d.close());f.store.close();rmSync(f.directory,{recursive:true,force:true});});
  const origin=`http://127.0.0.1:${server.address().port}`,url=origin+'/api/inbox/connections/telegram/receiving';
  const headers={Cookie:`account_session=${slot.token}`,Origin:origin,'Content-Type':'application/json','X-Session-Binding':auth.sessionBinding,'X-CSRF-Token':auth.csrf};
  const data={connectionId:'one',expectedRevision:0,expectedConnectionRevision:1};
  const post=(action,value,h=headers)=>fetch(url+'/'+action,{method:'POST',headers:h,body:JSON.stringify(value)});
  const status=async()=>{const r=await fetch(url,{headers});assert.equal(r.status,200);return r.json();};
  assert.equal((await status()).connections[0].state,'missing');
  for(const change of [{Cookie:''},{'X-CSRF-Token':''},{Origin:'https://other.test'}])assert.ok((await post('start',data,{...headers,...change})).status>=400);
  assert.equal((await post('start',{...data,send:true})).status,422);
  const guest=f.store.accountForMember('commons','guest'),gs=f.store.createAccountSessionSlot(),ga=f.store.loginAccountSession(gs.token,f.store.issueAccountAccessKey(guest.id),0);
  const gh={...headers,Cookie:`account_session=${gs.token}`,'X-Session-Binding':ga.sessionBinding,'X-CSRF-Token':ga.csrf};
  assert.deepEqual((await(await fetch(url,{headers:gh})).json()).connections,[]);
  assert.equal((await post('start',data,gh)).status,409);
  const before=f.store.now(),start=await post('start',data);assert.equal(start.status,200);
  const receipt=await start.json();assert.equal(receipt.revision,1);assert.ok(receipt.expiresAt>=before+86400000&&receipt.expiresAt<=f.store.now()+86400000);
  assert.equal((await post('start',data)).status,409);
  assert.ok(!JSON.stringify(await status()).includes(config.token));
  assert.equal((await service.syncReceiving(account.id,'one')).imported,1);
  assert.equal((await post('stop',{connectionId:'one',expectedRevision:1})).status,200);
  await assert.rejects(service.syncReceiving(account.id,'one'));assert.equal(polls,1);
  assert.equal(registry.status(config).state,'active');assert.equal(f.store.inbox.list(slot.token,auth.sessionBinding).sources.length,1);
  assert.equal((await post('start',{...data,expectedRevision:2})).status,200);
  f.store.logoutAccountSession(slot.token,auth.sessionRevision);
  assert.equal((await service.syncReceiving(account.id,'one')).imported,0);assert.equal(polls,2);
  assert.ok((await fetch(url,{headers})).status>=400);
});
