import {createRuntimePackage} from "../scripts/runtime-package.mjs";
import {pathToFileURL} from "node:url";
import {createOperatorPurge} from "../server/operator-purge.mjs";
// Authoring gate: the old identity-only route doubles could not catch tenant leaks,
// spoofed parties, restart loss, stale revisions or forged receipts. Real HTTP,
// SQLite and production crypto form this transport/lifecycle owner; no test seam.
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {RoomStore} from '../server/store.mjs';
import {initialRoom} from '../server/bootstrap.mjs';
import {createRoomServer} from '../server/http.mjs';
import {addRailMember,submittedTrial,acceptedReceipt} from '../scripts/record-rails-fixture.mjs';
import {backupRoom} from '../server/backup.mjs';
async function fixture(t){const dir=mkdtempSync(join(tmpdir(),'trial-http-')),filename=join(dir,'room.sqlite');const store=new RoomStore(filename);store.initialize(initialRoom());addRailMember(store,'worker');addRailMember(store,'outsider');store.initialize(initialRoom('other-room'));const keys=Object.fromEntries(['owner','worker','outsider'].map(id=>[id,store.issueAccessKey('commons',id)]));const server=createRoomServer({store});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{server.closeStreams();server.closeAllConnections();await new Promise(r=>server.close(r));store.close();rmSync(dir,{recursive:true,force:true});});const call=(actor,input,path='/api/rooms/commons/trial-tasks')=>fetch(origin+path,{method:input?'POST':'GET',headers:{'Content-Type':'application/json',...(actor?{Authorization:`Bearer ${keys[actor]??actor}`}:{})},...(input?{body:JSON.stringify(input)}:{})});return {get store(){return store;},call,dir,filename,keys};}
const data={action:'create',requestId:'once',taskId:'private-trial',candidateId:'worker',buyerId:'owner',demigodReqId:'req',title:'Private terms',trialScope:{hoursMax:'40',deliverableShape:'code-pr'},vettingRubric:[{criterion:'c1',weightBps:'10000'}],feePolicyRef:'record-only',budgetRecord:{note:'Budget recorded; no money'} };
const read=async(r,status)=>{assert.equal(r.status,status,await r.clone().text());return r.json();};
test('real trial API enforces tenant/party privacy, exact retries, revisions and room membership',async t=>{const f=await fixture(t);await read(await f.call(null,data),401);await read(await f.call('outsider',data),403);const first=await read(await f.call('owner',data),200);assert.equal(first.paymentStatus,'not_configured');assert.deepEqual(await read(await f.call('owner',data),200),first);await read(await f.call('owner',{...data,title:'Overwrite'}),409);await read(await f.call('owner',{...data,requestId:'other-id'}),409);await read(await f.call(null,null,'/api/rooms/commons/trial-tasks/private-trial'),401);await read(await f.call('outsider',null,'/api/rooms/commons/trial-tasks/private-trial'),403);await read(await f.call('worker',null,'/api/rooms/other-room/trial-tasks/private-trial'),403);await read(await f.call('worker',{action:'claim',taskId:'private-trial',requestId:'spoof',expectedRevision:0,candidateId:'outsider'}),422);await read(await f.call('owner',{action:'claim',taskId:'private-trial',requestId:'claim-owner',expectedRevision:0}),403);await read(await f.call('worker',{action:'claim',taskId:'private-trial',requestId:'claim-worker',expectedRevision:0}),200);await read(await f.call('worker',{action:'submit',taskId:'private-trial',requestId:'stale',expectedRevision:0,deliverableRef:'https://example.com'}),409);});
test('trusted bound receipts persist through online backup/restart and confirmed room deletion',async t=>{const f=await fixture(t);const receipt=acceptedReceipt(f.store);const result=f.store.trialTasks.verified('commons','trial-abc123',receipt.receiptId);assert.equal(result.state,'receipted');const capture=await backupRoom(f.filename,f.dir),recovered=new RoomStore(capture.filename);try{assert.equal(recovered.trialTasks.verified('commons',result.id,receipt.receiptId).candidateId,'worker');assert.deepEqual(recovered.trialTasks.read('commons','owner',result.id),result);const purge=createOperatorPurge(recovered),plan=purge.plan({targets:[{kind:'room',id:'commons'}],reason:'Synthetic confirmed cleanup',allowActiveMembers:true},'test-plan');purge.execute({planId:plan.planId,confirmToken:plan.confirmToken},'test-execute');for(const table of ['room_trial_tasks','room_trial_requests','room_vetting_keys','room_vetting_receipts'])assert.equal(recovered.db.prepare(`SELECT count(*) n FROM ${table}`).get().n,0);}finally{recovered.close();}submittedTrial(f.store,{id:'second-trial'});assert.throws(()=>f.store.trialTasks.apply('commons','owner',{action:'verdict',requestId:'forged',taskId:'second-trial',expectedRevision:2,rubricScores:receipt.rubricScores,verdict:'pass',receipt}),{code:'buyer_signoff_required'});f.store.buyerSignoff.create('commons','owner',{requestId:'second-loop',loopId:'second-loop',trialTaskId:'second-trial',buyerId:'owner',maxRounds:2});f.store.buyerSignoff.submit('commons','worker','second-loop',{requestId:'second-delivery',candidateId:'worker',deliverableRef:'https://example.com/delivery',sha256:'b'.repeat(64),summary:'Second delivery'});f.store.buyerSignoff.review('commons','owner','second-loop',{requestId:'second-review',decision:'accept'});await read(await f.call('owner',{action:'verdict',requestId:'wrong-binding',taskId:'second-trial',expectedRevision:2,rubricScores:receipt.rubricScores,verdict:'pass',receipt}),422);assert.equal(f.store.trialTasks.raw('commons','second-trial').state,'submitted');const quote={action:'quote',requestId:'fee-quote',placementValueMinor:'10000',currency:'USD',trialHoursMax:'2',hourlyRateMinor:'100'};const example=await read(await f.call('owner',quote),200);assert.equal(example.hypothetical,true);assert.equal(example.paymentStatus,'not_configured');assert.deepEqual(await read(await f.call('owner',quote),200),example);});

test('real API keys require read/write scopes independently of bound candidate identity',async t=>{const f=await fixture(t),identity=f.store.identities.create('API candidate');f.store.identities.link(f.keys.owner,'commons',{identityId:identity.identityId,memberId:'api-worker',displayName:'API worker',permissions:['accept_work']});const key=f.store.agentPlugin.issueApiKey({identityId:identity.identityId,scopes:['rooms:read']});await read(await f.call('owner',{...data,requestId:'api-trial',taskId:'api-trial',candidateId:'api-worker'}),200);const readKey=`rak_${key.secret}`;await read(await f.call(readKey,null,'/api/rooms/commons/trial-tasks/api-trial'),200);await read(await f.call(readKey,{action:'claim',requestId:'denied-scope',taskId:'api-trial',expectedRevision:0}),403);const writing=f.store.agentPlugin.issueApiKey({identityId:identity.identityId,scopes:['rooms:write']});await read(await f.call(`rak_${writing.secret}`,{action:'claim',requestId:'allowed-scope',taskId:'api-trial',expectedRevision:0}),200);await read(await f.call(`rak_${writing.secret}`,null,'/api/rooms/commons/trial-tasks/api-trial'),403);});

test('existing committed v38 data upgrades additively without changing indexed-message schema or credentials',async t=>{const f=await fixture(t),runtime=join(f.dir,'old-runtime');createRuntimePackage({repository:process.cwd(),commit:'48264de7e07c281090c203265df8d9a929472e59',destination:runtime});const {RoomStore:OldStore}=await import(pathToFileURL(join(runtime,'server/store.mjs')));const filename=join(f.dir,'upgrade.sqlite'),old=new OldStore(filename);old.initialize(initialRoom());const key=old.issueAccessKey('commons','owner');old.command(key,'commons',{id:'retained-message',type:'message.posted',data:{messageId:'retained',body:'Previous committed data'}});old.close();const updated=new RoomStore(filename);try{assert.equal(updated.storagePlatform.version(updated.db),38);assert.equal(updated.authenticate(key,'commons').member.id,'owner');assert.equal(updated.room('commons').state.messages.find(m=>m.id==='retained').body,'Previous committed data');for(const table of ['room_trial_tasks','room_trial_requests','room_vetting_keys','room_vetting_receipts','demigod_offer_profiles','demigod_offer_requests','demigod_contracts','demigod_contract_requests','buyer_signoff_loops','buyer_signoff_requests'])assert.equal(updated.db.prepare(`SELECT count(*) n FROM ${table}`).get().n,0);}finally{updated.close();}});
