// Generated by scripts/build-capabilities.mjs — do not hand-edit.
// Regenerate: node scripts/build-capabilities.mjs
// Capability families inventory the route table at build time (#601).
export const CAPABILITIES = Object.freeze({
  "agent-identities": true,
  "agent-invites": true,
  "agent-keys": true,
  "agent-rooms": true,
  "guest-agent-links": true,
  "directory": true,
  "agent-inbox": true,
  "collab": true,
  "webhooks": true,
  "public-face": true,
  "spend-allowance": true,
  "web-fetch": true,
});
