// GENERATED by scripts/procedures-index.mjs — do not hand-edit.
// Source of truth: docs/procedures/*.md. Regenerate with:
//   node scripts/procedures-index.mjs
export const PROCEDURES_SCHEMA_VERSION = "1";
export const PROCEDURES_INDEX = Object.freeze([
  Object.freeze({
    id: "ops.incident-triage",
    title: "Incident triage",
    version: "1.0.0",
    author: "jill (lane burn-shared-procedures)",
    source_room: "muse-room",
    updated: "2026-10-06",
    status: "active",
    path: "docs/procedures/incident-triage.md",
    body: "# Incident triage\n\nThe first minutes of an incident. Abridged from the project-room incident\nrunbook — during a live incident, use this as a checklist, not a textbook.\n\n## Severity levels\n\nPick the **highest** severity that matches. When in doubt, start higher — you\ncan always downgrade, and upgrading late costs time.\n\n| Severity | Definition |\n|----------|------------|\n| **SEV1** | Service down or broadly unusable, or data at risk (corruption, loss, suspected breach). |\n| **SEV2** | Core feature degraded for many users; partial data loss. |\n| **SEV3** | Limited impact: intermittent errors, one endpoint slow, minor feature broken. No data loss. |\n| **SEV4** | No user impact: flaky monitor, noisy alert, cosmetic issue, or fixed before it affected anyone. |\n\nSeverity is about user impact and data risk, not about how hard the fix looks.\n\n## First five minutes\n\n1. Declare the incident in the room: severity, what is observed, who is\n   incident commander.\n2. Name the roles out loud (one person per role, one role per person at a\n   time): incident commander, responder, communicator.\n3. Check `/api/health` first — per-check rows carry `status`, `detail`, and\n   `latencyMs`. Trust the health payload over assumptions.\n4. Stabilize before diagnosing: stop the bleeding (roll back, shed load,\n   freeze deploys), then investigate.\n5. Communicate early and briefly: what is broken, who is affected, what is\n   being done, when the next update lands.\n\n## After\n\nLog a timeline while it is fresh: detection, declaration, each action, and\nresolution. A change merges only when the lesson is recorded — append what\nwas learned and what now guards against recurrence."
  }),
  Object.freeze({
    id: "swarm.claim-protocol",
    title: "Work-claim protocol",
    version: "1.0.0",
    author: "jill (lane burn-shared-procedures)",
    source_room: "muse-room",
    updated: "2026-10-06",
    status: "active",
    path: "docs/procedures/claim-protocol.md",
    body: "# Work-claim protocol\n\nHow agents coordinate on shared surfaces without colliding. Ported from the\nvalidated swarm procedures (muse-room, 2026-09-16).\n\n## Before touching a shared surface\n\nShared surfaces: the server entrypoint, the store, the schema, storage,\nmigrations, shared runtime packaging, deployment surfaces.\n\n1. Post one precise claim to the room's work-claims board: name the exact\n   files, the schema impact (or \"none\"), and the branch.\n2. Prefer new-file-only slices — no proposal needed for those, just build.\n3. One owner per branch/slice. Never take a branch another agent claimed.\n4. Respect declared merge-freeze / batch-push windows; do not merge during\n   them.\n5. Rebase onto the current main tip immediately before final validation.\n6. Never treat silence as permission where an overlapping claim exists.\n\n## Ownership freshness\n\nTreat ownership knowledge older than ~15 minutes as expired: re-read the live\nwork-claims board in the same session before asserting \"no owner\". First claim\nwins — on collision, stand down the duplicate and fold anything it lacks\ninto the first claimant's work.\n\n## Handoff shape\n\nA releaser posts: what was released, at which main SHA, and the constraint\nthat must be preserved. The receiver records the claim with the exact paths\nand acknowledges before editing. No acknowledgment, no edits."
  }),
  Object.freeze({
    id: "swarm.merge-checklist",
    title: "Merge checklist",
    version: "1.0.0",
    author: "jill (lane burn-shared-procedures)",
    source_room: "muse-room",
    updated: "2026-10-06",
    status: "active",
    path: "docs/procedures/merge-checklist.md",
    body: "# Merge checklist\n\nEvery PR merges only when all of these hold. Ported from the validated swarm\nprocedures (muse-room, 2026-09-16).\n\n1. PR state is MERGEABLE / CLEAN.\n2. All hosted checks green on the exact head (contract, lint, tests,\n   cloudflare, browser, plus approvals).\n3. Full local `npm run check` — 0 failures.\n4. Rebase onto the current main tip immediately before final validation;\n   never merge a head more than ~2h behind main without rebasing.\n5. Merge only after the reviewer's explicit APPROVE on the exact head\n   (lander rule). Never merge while a CHANGES REQUESTED verdict is open\n   (merge-hold rule).\n6. On conflicts in another lane's file: stop and ask in the room rather than\n   resolving blindly.\n\n## Merge receipt\n\nPost a SHA-pinned receipt to the room when the PR merges:\n\n- PR number and merge commit SHA (short).\n- What changed (files added/edited, one line each).\n- Schema / storage / migration impact, or the explicit word \"none\".\n- Check counts: hosted (x/y green) and local (`npm run check`: pass/fail).\n- The sentence \"claim released\" (or which claim remains open).\n\nConsequential room posts (plans, ownership claims, handoffs, votes) get a\nread-back check: fetch the event log and confirm the message appears.\n\"Posted ok\" is submission, not delivery."
  })
]);
