// Generated from strings/en.json by scripts/build-ui-strings.mjs.
export default {
  "_meta": {
    "locale": "en",
    "note": "Seed strings catalog for the i18n harness (backlog Q012). Seeded from server/notify-email.mjs notification copy. Placeholders are named ({count}), never positional ({0}, %s). This is the catalog future code migrates hardcoded strings into; the harness's hardcoded-ui-string rule ratchets against it."
  },
  "email.batch.subject_many": "{count} things need you in Room",
  "email.batch.subject_one": "Something needs you in Room",
  "email.brief.subject": "Your Room brief",
  "email.cta.open_in_room": "Open in Room",
  "email.cta.unsubscribe": "Unsubscribe",
  "email.row.fallback_head": "An update is waiting in Room",
  "human.workNoReview": "No review · Advanced options",
  "human.copy.001": "<div class=\"assistant-heading\"><strong>Room</strong><span id=\"room-assistant-status\"></span><button type=\"button\" id=\"assistant-setup\" class=\"text-button\">Connect</button><button type=\"button\" id=\"human-project-open\" class=\"text-button\">Project</button></div><details id=\"assistant-activity\"><summary>Activity</summary><div id=\"assistant-runs\"></div></details><p id=\"assistant-error\" class=\"form-hint\" role=\"status\"></p><button type=\"button\" id=\"assistant-retry\" class=\"text-button\" hidden>Retry request</button><button type=\"button\" id=\"assistant-review\" class=\"text-button\" hidden>Review current request</button><button type=\"button\" id=\"assistant-discard\" class=\"text-button\" hidden>Dismiss</button>",
  "human.copy.002": "Ask the room assistant in this shared conversation",
  "human.copy.003": "<input id=\"human-advanced\" type=\"checkbox\"> Show advanced agent controls",
  "human.copy.004": "Your shared work and results.",
  "human.copy.005": "In progress · reported",
  "human.copy.006": "<p>No tasks yet. Start with a conversation.</p>",
  "human.copy.007": "<form><div class=\"dialog-head\"><h2 id=\"assistant-setup-title\">Connect Room</h2></div><p>Choose an agent to coordinate this room. Shared prompts and activity are visible to everyone here. This does not start an outside agent.</p><label>Coordinator<select name=\"coordinatorMemberId\" required></select></label><button type=\"button\" id=\"assistant-enroll\" class=\"button ghost\">Add an agent</button><p id=\"assistant-setup-error\" role=\"alert\"></p><div class=\"form-actions\"><button type=\"button\" data-close-setup class=\"button ghost\">Cancel</button><button type=\"submit\" class=\"button primary\">Connect</button></div></form>",
  "human.copy.008": "<option value=\"\">Choose an agent</option>",
  "human.copy.009": "Waiting for connection",
  "human.copy.010": "Waiting for assistant",
  "human.copy.011": "Resuming · waiting for confirmation",
  "human.copy.012": "Pausing · waiting for confirmation",
  "human.copy.013": "Stopping · waiting for confirmation",
  "human.copy.014": "Assistant service unavailable",
  "human.copy.015": "That request is closed. Your message is still in the conversation.",
  "human.copy.016": "Review the current activity, then choose Retry request to confirm applying your already-posted message.",
  "human.copy.017": "<form><div class=\"dialog-head\"><h2 id=\"human-share-title\">Share result</h2></div><p>Write the result here, then review it before saving. It will be shared with this room.</p><label>Result<textarea name=\"body\" rows=\"5\" maxlength=\"4000\" required></textarea></label><p id=\"human-share-error\" role=\"alert\"></p><button type=\"button\" id=\"human-share-refresh\" class=\"button ghost\" hidden>Review updated task</button><div class=\"form-actions\"><button type=\"button\" data-close-share class=\"button ghost\">Cancel</button><button type=\"submit\" class=\"button primary\">Review result</button></div><details><summary>Use an existing draft</summary><div id=\"human-existing-drafts\"></div></details></form>",
  "human.copy.018": "This task is no longer available. Your draft is kept here; cancel to discard it.",
  "human.copy.019": "Updated task: {fragmentA}. Review your draft, then choose Review result to post it against the current task.",
  "human.copy.020": "Draft was not saved: {fragmentA}. Review the updated task before posting again, or cancel to discard this draft.",
  "human.copy.021": "Draft not confirmed: {fragmentA}. Retry preserves the original draft.",
  "human.copy.022": "Retry original draft",
  "human.copy.023": "An earlier assistant request needs confirmation. Retry preserves the original request.",
  "human.copy.024": "<p>No drafts yet.</p>",
  "signin.copy.001": "The browser account changed. Sign in again.",
  "signin.copy.002": "Sign-in didn’t complete. Try again.",
  "signin.copy.003": "Couldn’t sign in. Try again.",
  "signin.copy.004": "<div class=\"signin-welcome\"><button type=\"button\" class=\"button primary\" data-password-mode=\"signup\">Create account</button><button type=\"button\" class=\"button secondary\" data-password-mode=\"login\">Log in</button></div>",
  "signin.copy.005": "<form data-signin-form=\"terms\"><p class=\"form-hint\">The terms changed. Read the <a href=\"/terms\">Terms</a> and <a href=\"/privacy\">Privacy Policy</a>, then continue.</p><button class=\"button primary\" type=\"submit\" {fragmentA}>Agree and continue</button></form>",
  "signin.copy.006": "<p class=\"form-hint\">This link is for a different account.</p><button type=\"button\" class=\"button primary\" data-magic-switch {fragmentA}>Switch account</button>",
  "signin.copy.007": "<button type=\"button\" class=\"button primary\" data-recovery-option=\"reset\" data-reset-password>Reset password</button><button type=\"button\" class=\"text-button\" data-recovery-option=\"magic\" data-email-method=\"magic\">Email me a sign-in link</button>",
  "signin.copy.008": "<p class=\"form-hint\">If an account uses {fragmentA}, check your email for a password reset link.</p><button type=\"button\" class=\"text-button\" data-recovery-option=\"reset\" data-reset-password>Use a different email</button>",
  "signin.copy.009": "<form data-signin-form=\"reset-consume\"><label>New password <input name=\"newPassword\" type=\"password\" required autocomplete=\"new-password\" minlength=\"10\" maxlength=\"256\"></label><label>Confirm new password <input name=\"confirmPassword\" type=\"password\" required autocomplete=\"new-password\" minlength=\"10\" maxlength=\"256\"></label><button class=\"button primary\" type=\"submit\" {fragmentA}>Reset password</button></form>",
  "signin.copy.010": "<form data-signin-form=\"reset-request\"><label>Email <input name=\"email\" type=\"email\" required autocomplete=\"email\" maxlength=\"254\" value=\"{fragmentA}\"></label><button class=\"button primary\" type=\"submit\" {fragmentB}>Email password reset link</button></form><button type=\"button\" class=\"button ghost\" data-recovery-option=\"magic\" data-email-method=\"magic\">Email me a sign-in link instead</button>",
  "signin.copy.011": "<form data-signin-form=\"password\" autocomplete=\"on\">\n        <label>Email <input name=\"email\" type=\"email\" required autocomplete=\"email\" maxlength=\"254\" value=\"{fragmentA}\"></label>\n        <label>Password <input name=\"password\" type=\"password\" required autocomplete=\"{fragmentB}\" maxlength=\"256\" {fragmentC}></label>\n        <button type=\"button\" class=\"text-button\" data-password-visibility aria-pressed=\"false\">Show password</button>\n        {fragmentD}\n        <button class=\"button primary\" type=\"submit\" {fragmentE}>{fragmentF}</button>\n        <button type=\"button\" class=\"text-button\" data-password-mode=\"{fragmentG}\">{fragmentH}</button>\n        <button type=\"button\" class=\"text-button\" data-forgot-password>Forgot password?</button>\n        <details class=\"signin-more\"><summary>Other options</summary><button type=\"button\" class=\"text-button\" data-email-method=\"magic\">Email me a sign-in link</button></details>\n      </form>",
  "signin.copy.012": "<form data-signin-form=\"magic-code\" autocomplete=\"on\">\n      <p class=\"form-hint\">Check {fragmentA} for your sign-in link.</p>\n      {fragmentB}\n      <button type=\"button\" class=\"text-button\" data-magic-manual-code>{fragmentC}</button>\n      <button type=\"button\" class=\"text-button\" data-magic-restart>Use a different email</button>\n    </form>",
  "signin.copy.013": "<label>Sign-in code <input name=\"code\" required autocomplete=\"one-time-code\" maxlength=\"128\"></label><button class=\"button primary\" type=\"submit\" {fragmentA}>Sign in</button>",
  "signin.copy.014": "Use a code instead",
  "signin.copy.015": "<form data-signin-form=\"magic-request\" autocomplete=\"on\">\n      <label>Email <input name=\"email\" type=\"email\" required autocomplete=\"email\" maxlength=\"254\" value=\"{fragmentA}\"></label>\n      <button class=\"button primary\" type=\"submit\" {fragmentB}>Email me a sign-in link</button>\n\n    </form>",
  "signin.copy.016": "Sign-in didn’t complete. Try again.",
  "signin.copy.017": "The browser account changed. Sign in again.",
  "signin.copy.018": "The browser account changed. Sign in again.",
  "signin.copy.019": "Request a new password reset link.",
  "signin.copy.020": "Use 10–256 characters for your password.",
  "signin.copy.021": "Passwords don’t match.",
  "signin.copy.022": "The browser account changed. Sign in again.",
  "signin.copy.023": "Password reset. Sign in to continue.",
  "signin.copy.024": "Use 10–256 characters for your password.",
  "signin.copy.025": "Couldn’t create the account. Try again.",
  "signin.copy.026": "Check your email for a verification code.",
  "signin.copy.027": "Email delivery isn’t configured, so this account stays unverified.",
  "signin.copy.028": "Check your email for a sign-in link.",
  "signin.copy.029": "Email delivery isn’t configured on this Room, so no sign-in link was sent. If this email is already registered, sign in instead.",
  "signin.copy.030": "Email delivery isn’t configured on this Room.",
  "signin.copy.031": "Couldn’t send the sign-in link. Try again.",
  "signin.copy.032": "This sign-in link is incomplete or invalid.",
  "signin.copy.033": "{fragmentA} Request a new link.",
  "signin.copy.034": "Signing you in…",
  "invite.copy.001": "Name must be 80 characters or fewer.",
  "invite.copy.002": "Choose contribute, collaborate, or review.",
  "invite.copy.003": "Invalid agent invite",
  "invite.copy.004": "Invalid Room address",
  "invite.copy.005": "Join me in Project Room: {fragmentA}\nConnect with the Room MCP server, then call room_check_access.",
  "invite.copy.006": "node scripts/agent-inbox.mjs join {fragmentA} ./room-connection --name \"My agent\"\nReview the room and permissions, then repeat with --accept. Keep and reuse room-connection to resume or join another room. No human account is required. This connects room access; a running host is needed to answer requests.",
  "invite.copy.007": "{fragmentA}\nIf you run the Room client locally:\n{fragmentB}",
  "invite.copy.008": "Invite could not be confirmed.",
  "invite.copy.009": "Select and copy the invite link(s).",
  "invite.copy.010": "Invite could not be confirmed.",
  "invite.copy.011": "Invite ready. Copy the link and give it to your agent.",
  "invite.copy.012": "{fragmentA} invites ready. Copy the links — each works once.",
  "invite.copy.013": "{fragmentA} of {fragmentB} invites ready; the next mint failed ({fragmentC}). Copy what you have.",
  "invite.copy.014": "Could not create an invite. Check your room permissions.",
  "invite.copy.015": "Copied the invite link. Share it with your agent.",
  "invite.copy.016": "Copied {fragmentA} invite links. Share them with your agents.",
  "squads.copy.001": "<article class=\"squad-card\" data-squad-id=\"{fragmentA}\">\n    <h4>@squad/{fragmentB}{fragmentC}{fragmentD}</h4>\n    <p class=\"squad-goal\">{fragmentE}</p>\n    <dl class=\"squad-meta\">\n      <div><dt>Channel</dt><dd>{fragmentF}</dd></div>\n      <div><dt>Members</dt><dd><ul class=\"squad-roster\">{fragmentG}</ul></dd></div>\n    </dl>\n  </article>",
  "squads.copy.002": "<form class=\"squads-create\" data-squad-action=\"create\">\n    <input name=\"name\" required maxlength=\"64\" pattern=\"[A-Za-z0-9_-]{1,64}\" placeholder=\"squad name\" aria-label=\"Squad name\">\n    <input name=\"goal\" maxlength=\"500\" placeholder=\"goal (optional)\" aria-label=\"Squad goal\">\n    <fieldset><legend>Members (up to 12 including you)</legend>{fragmentA}</fieldset>\n    <button type=\"submit\">create squad</button>\n  </form>",
  "squads.copy.003": "{fragmentA}<p class=\"squads-empty\">No squads yet. Mention one as <code>@squad/&lt;name&gt;</code> to fan out to every member (at most 12).</p>",
  "squads.copy.004": "Could not load squads.",
  "squads.copy.005": "Squad action failed.",
  "squads.copy.006": "Disband @squad/{fragmentA}? The squad stops fanning out mentions.",
  "push.copy.001": "Notify me of mentions and DMs",
  "push.copy.002": "Subscription was not saved for this session",
  "push.copy.003": "Mentions and DMs are on for this browser.",
  "push.copy.004": "Mentions are on for this browser; DMs are off.",
  "push.copy.005": "DMs are on for this browser; mentions are off.",
  "push.copy.006": "Push is off for this browser — nothing here will notify you.",
  "push.copy.007": "Preferences saved here; notification delivery is unavailable.",
  "push.copy.008": "Preferences saved here; this browser cannot receive notifications.",
  "push.copy.009": "Notifications are blocked in this browser.",
  "push.copy.010": "This browser could not turn on notifications.",
  "push.copy.011": "Preferences were not saved",
  "push.copy.012": "Notification preferences saved.",
  "push.copy.013": "Preferences could not be saved.",
  "push.copy.014": "Notifications are blocked in this browser.",
  "push.copy.015": "This browser could not turn on notifications.",
  "guide.instructions": "<ol class=\"connect-steps\"><li>Open Invite and create an agent invitation for this room.</li><li>Copy these instructions and paste them into your AI along with the invite link.</li><li>Your agent needs room tools and a running host to answer. Return here to chat once it connects.</li></ol><p>No invitation? Ask a room member for one, or use your own room's Invite button.</p>",
  "board.mine.copy.001": "Your lease ended",
  "board.mine.copy.002": "Your lease ends in {fragmentA}",
  "board.mine.copy.003": "You are tagged to review · {fragmentA}",
  "board.mine.copy.004": "No update for {fragmentA}",
  "board.mine.copy.005": "Nothing needs you",
  "directory.card.copy.001": "<p class=\"form-hint\">No directory card available.</p>",
  "directory.card.copy.002": "No live wake/bond data",
  "join.alreadyJoined": "You already joined this room. Go back to sign-in and open the room, or use your saved agent credential.",
  "profile.title": "Profile",
  "profile.form": "<form data-form=\"account-profile\" class=\"settings-form\"><label>Account display name <input name=\"displayName\" autocomplete=\"nickname\" maxlength=\"80\" value=\"{name}\"></label><p class=\"form-hint\">Your account name. Names you use in rooms stay the same.</p><button type=\"submit\" class=\"button primary\">Save</button></form>",
  "profile.loading": "Loading profile…",
  "profile.saving": "Saving profile…",
  "profile.failed": "Could not load the profile.",
  "profile.save_failed": "Could not save the profile.",
  "profile.close": "Close",
  "profile.editing": "editing your profile",
  "file.download.action": "Download {filename}",
  "file.download.pending": "Downloading…",
  "file.download.started": "Download started",
  "file.download.unavailable": "File unavailable",
  "file.download.retry": "Couldn’t download. Try again.",
  "human.decisionRationaleNotice": "<p class=\"form-hint\">Your reason will be posted to the room.</p>",
  "human.decisionReceiptUnknown": "Save receipt could not be confirmed",
  "human.decisionRationaleChanged": "Your reason was posted. Review the changed result before deciding."
};
