// Classic service worker build (HB-3a). iOS 16.4 through 18.3 home-screen
// workers do not accept register({ type: "module" }). This inlines
// src/human-push-display.js so push-sw.js has no import. Run after editing
// the display module: node scripts/build-push-sw.mjs
import { readFileSync, writeFileSync } from "node:fs";

const display = readFileSync(new URL("../src/human-push-display.js", import.meta.url), "utf8")
  .replace(/^export function /gm, "function ");

const handlers = `
const CACHE_NAME = "room-pwa-v1";
const CACHE_ALLOW = [
  "/offline.html",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/maskable-512.png",
  "/icons/apple-touch-icon-180.png"
];

self.addEventListener("install", event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await cache.addAll(CACHE_ALLOW);
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(key => key !== CACHE_NAME).map(key => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", event => {
  if (event.request.mode === "navigate") {
    event.respondWith((async () => {
      try {
        return await fetch(event.request);
      } catch {
        const cache = await caches.open(CACHE_NAME);
        const offline = await cache.match("/offline.html");
        return offline || new Response("Room is offline.", { status: 503, headers: { "Content-Type": "text/plain; charset=utf-8" } });
      }
    })());
    return;
  }
  // The offline page's own icon: network first, cached copy when the network
  // fails, so the no-network page keeps its mark. Everything else stays
  // network-only (assets are served no-store).
  const path = new URL(event.request.url).pathname;
  if (CACHE_ALLOW.includes(path)) {
    event.respondWith((async () => {
      try {
        return await fetch(event.request);
      } catch (error) {
        const cache = await caches.open(CACHE_NAME);
        const cached = await cache.match(path);
        if (cached) return cached;
        throw error;
      }
    })());
    return;
  }
  event.respondWith(fetch(event.request));
});

self.addEventListener("push", event => {
  let payload = {};
  try { payload = event.data && event.data.json ? event.data.json() : {}; } catch { payload = {}; }
  const note = notificationFromPush(payload);
  const options = { body: note.body, tag: note.tag, renotify: false, data: note.data };
  const actionsSupported = typeof Notification === "function" && "actions" in Notification.prototype;
  if (actionsSupported && note.actions.length) options.actions = note.actions;
  const badge = note.needsMeCount;
  event.waitUntil(Promise.all([
    self.registration.showNotification(note.title, options),
    (async () => {
      if (badge === null) return;
      if (badge === 0 && navigator.clearAppBadge) await navigator.clearAppBadge();
      else if (badge > 0 && navigator.setAppBadge) await navigator.setAppBadge(badge);
    })()
  ]));
});

self.addEventListener("notificationclick", event => {
  event.notification.close();
  const data = event.notification.data || {};
  const target = typeof data.url === "string" && data.url ? data.url : new URL(self.registration.scope).href;
  // Approve, reject, and reply are HB-3b. Until that decide path exists, an
  // action click opens the same item a plain click opens.
  event.waitUntil((async () => {
    const windows = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
    const scope = new URL(self.registration.scope);
    for (const client of windows) {
      let origin = "";
      try { origin = new URL(client.url).origin; } catch { origin = ""; }
      if (origin !== scope.origin) continue;
      if (client.focus) await client.focus();
      if (client.navigate) await client.navigate(target);
      return;
    }
    await self.clients.openWindow(target);
  })());
});
`;

const banner = `// Classic service worker (HB-3a). Generated by scripts/build-push-sw.mjs.
// No import: iOS 16.4–18.3 home-screen workers cannot load a module worker.
// Caches only the offline page and icons. App code and API responses stay
// network-only (assets are served no-store).
`;

writeFileSync(new URL("../push-sw.js", import.meta.url), banner + display + handlers);
console.log("wrote push-sw.js");
