// W008: shared procedure library index generator (docs-first).
//
// Source of truth: docs/procedures/*.md, each with YAML frontmatter:
//   id, title, version (semver), author, source_room, updated (YYYY-MM-DD),
//   status (active|deprecated, default active).
//
// This script validates every file and bakes a frozen index into
// deploy/procedures-index.mjs, which the discovery surface serves at
// GET /procedures (read-only, global namespace: every room reads the same
// bytes). Run it after adding or editing a procedure:
//
//   node scripts/procedures-index.mjs
//   node scripts/procedures-index.mjs --check   # CI-style: exit 1 when stale
//
// The library is read-only by design in v1: there is no write API and the
// served doc advertises none. New versions land through pull requests that
// edit the markdown and regenerate this index.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

export const PROCEDURES_SCHEMA_VERSION = "1";

const REQUIRED_FIELDS = ["id", "title", "version", "author", "source_room", "updated"];
const ID_RE = /^[a-z0-9]+(\.[a-z0-9-]+)+$/;
const VERSION_RE = /^\d+\.\d+\.\d+$/;
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
const STATUSES = new Set(["active", "deprecated"]);

export function parseProcedureFile(text, filename) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(text);
  if (!match) throw new Error(`${filename}: missing frontmatter block (--- ... ---)`);
  const meta = {};
  for (const line of match[1].split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const kv = /^([A-Za-z0-9_]+):\s*(.*)$/.exec(line);
    if (!kv) throw new Error(`${filename}: frontmatter line is not "key: value": ${line}`);
    meta[kv[1]] = kv[2].trim();
  }
  for (const field of REQUIRED_FIELDS) {
    if (!meta[field]) throw new Error(`${filename}: missing required frontmatter field: ${field}`);
  }
  if (!ID_RE.test(meta.id)) {
    throw new Error(`${filename}: id must be a dotted lowercase namespace (e.g. swarm.claim-protocol), got "${meta.id}"`);
  }
  if (!VERSION_RE.test(meta.version)) {
    throw new Error(`${filename}: version must be semver x.y.z, got "${meta.version}"`);
  }
  if (!DATE_RE.test(meta.updated) || Number.isNaN(Date.parse(meta.updated))) {
    throw new Error(`${filename}: updated must be a YYYY-MM-DD date, got "${meta.updated}"`);
  }
  const status = meta.status === undefined ? "active" : meta.status;
  if (!STATUSES.has(status)) {
    throw new Error(`${filename}: status must be one of ${[...STATUSES].join("|")}, got "${meta.status}"`);
  }
  const body = match[2].trim();
  if (!body) throw new Error(`${filename}: body is empty`);
  return { meta: { ...meta, status }, body };
}

export function buildProceduresIndex(proceduresDir) {
  const files = readdirSync(proceduresDir)
    .filter(name => name.endsWith(".md") && name !== "README.md")
    .sort();
  const seen = new Map();
  const index = [];
  for (const file of files) {
    const { meta, body } = parseProcedureFile(readFileSync(join(proceduresDir, file), "utf8"), file);
    if (seen.has(meta.id)) {
      throw new Error(`duplicate procedure id "${meta.id}" in ${file} and ${seen.get(meta.id)}`);
    }
    seen.set(meta.id, file);
    index.push({
      id: meta.id,
      title: meta.title,
      version: meta.version,
      author: meta.author,
      source_room: meta.source_room,
      updated: meta.updated,
      status: meta.status,
      path: `docs/procedures/${file}`,
      body,
    });
  }
  index.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  return index;
}

function renderModule(index) {
  const entries = index.map(proc => {
    const fields = ["id", "title", "version", "author", "source_room", "updated", "status", "path", "body"]
      .map(key => `    ${key}: ${JSON.stringify(proc[key])}`)
      .join(",\n");
    return `  Object.freeze({\n${fields}\n  })`;
  });
  return `// GENERATED by scripts/procedures-index.mjs — do not hand-edit.
// Source of truth: docs/procedures/*.md. Regenerate with:
//   node scripts/procedures-index.mjs
export const PROCEDURES_SCHEMA_VERSION = ${JSON.stringify(PROCEDURES_SCHEMA_VERSION)};
export const PROCEDURES_INDEX = Object.freeze([
${entries.join(",\n")}
]);
`;
}

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const proceduresDir = join(repoRoot, "docs", "procedures");
const outPath = join(repoRoot, "deploy", "procedures-index.mjs");

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  const index = buildProceduresIndex(proceduresDir);
  const rendered = renderModule(index);
  if (check) {
    const current = readFileSync(outPath, "utf8");
    if (current !== rendered) {
      console.error("deploy/procedures-index.mjs is stale: run node scripts/procedures-index.mjs");
      process.exit(1);
    }
    console.log(`procedures index fresh: ${index.length} procedures`);
  } else {
    writeFileSync(outPath, rendered);
    console.log(`wrote ${outPath}: ${index.length} procedures`);
  }
}
