// W009: build-time embed of the wiki planes for the read API.
//
// The wiki read API (server/wiki-read-api.mjs) serves this data in every
// runtime, including the bundled Cloudflare worker, which has no filesystem.
// Regenerate after any wiki-plane change:
//   node scripts/wiki-build.mjs            write server/wiki-data.mjs
//   node scripts/wiki-build.mjs --check    fail if server/wiki-data.mjs is stale (CI gate)
// The parsers live in server/wiki-parse.mjs (pure, no I/O of their own);
// this script does the file reading.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parseProcedures, parseRunbooks, parseWikiEntries } from "../server/wiki-parse.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "server", "wiki-data.mjs");

const PLANES = [
  "docs/ROOM-WIKI.md",
  "docs/history/ROOM-PROCEDURES.md",
  "docs/*RUNBOOK*.md",
];

export function buildWikiData(repoRoot = root) {
  const procedures = parseProcedures(readFileSync(join(repoRoot, "docs", "history", "ROOM-PROCEDURES.md"), "utf8"));
  const entries = parseWikiEntries(readFileSync(join(repoRoot, "docs", "ROOM-WIKI.md"), "utf8"));
  const names = readdirSync(join(repoRoot, "docs")).filter(name => /RUNBOOK.*\.md$/i.test(name)).sort();
  const runbooks = parseRunbooks(
    names.map(name => ({ path: `docs/${name}`, text: readFileSync(join(repoRoot, "docs", name), "utf8") })),
  );
  return { procedures, entries, runbooks };
}

function render(data) {
  return `// GENERATED by node scripts/wiki-build.mjs — do not edit by hand.\n` +
    `// Source planes: ${PLANES.join(", ")}.\n` +
    `// Regenerate after any wiki-plane change: node scripts/wiki-build.mjs\n` +
    `export const WIKI_DATA = ${JSON.stringify(data, null, 2)};\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  const data = buildWikiData();
  const rendered = render(data);
  if (check) {
    const current = readFileSync(OUT, "utf8");
    if (current !== rendered) {
      console.error("wiki-build: server/wiki-data.mjs is stale — run node scripts/wiki-build.mjs and commit it");
      process.exit(1);
    }
    console.log(`wiki-build: OK (server/wiki-data.mjs current: ${data.procedures.length} procedures, ${data.entries.length} entries, ${data.runbooks.length} runbooks)`);
  } else {
    writeFileSync(OUT, rendered);
    console.log(`wiki-build: wrote server/wiki-data.mjs (${data.procedures.length} procedures, ${data.entries.length} entries, ${data.runbooks.length} runbooks)`);
  }
}
