#!/usr/bin/env python3
# Guild-03 mutation spec: 15 units, ~50 mutants across the routes-mcp slice.
SPEC = {"units": [
{"id": "M1", "file": "server/feedback-routes.mjs",
 "tests": ["tests/feedback-routes.test.js"],
 "mutants": [
  {"id": "a", "kind": "flipped-guest-check",
   "old": 'if (!readMethod(req.method) && isGuestAgentMemberId(lane)) {',
   "new": 'if (!readMethod(req.method) && !isGuestAgentMemberId(lane)) {'},
  {"id": "b", "kind": "flipped-lane-mismatch",
   "old": 'if (data?.agent?.lane && data.agent.lane !== lane) {',
   "new": 'if (data?.agent?.lane && data.agent.lane === lane) {'},
  {"id": "c", "kind": "off-by-one-limiter",
   "old": 'if (b.tokens < 1) { buckets.set(lane, b); return false; }',
   "new": 'if (b.tokens <= 1) { buckets.set(lane, b); return false; }'},
  {"id": "d", "kind": "dropped-head-guard",
   "old": '    if (head) return json(res, 200, { notifications: [], drained: false }, head);\n',
   "new": ''},
 ]},
{"id": "M2", "file": "server/mcp-http.mjs",
 "tests": ["tests/mcp-empty-bearer.test.js", "tests/mcp-dotted-aliases.test.js"],
 "mutants": [
  {"id": "a", "kind": "flipped-auth-status",
   "old": 'return reply.error?.code === MCP_AUTH_REQUIRED ? 401 : 200;',
   "new": 'return reply.error?.code !== MCP_AUTH_REQUIRED ? 401 : 200;'},
  {"id": "b", "kind": "bearer-case-sensitive",
   "old": '/^bearer /i.test(authorization) ? authorization.slice("Bearer ".length) : ""',
   "new": '/^bearer /.test(authorization) ? authorization.slice("Bearer ".length) : ""'},
  {"id": "c", "kind": "off-by-one-id-length",
   "old": 'typeof message.method !== "string"\n    || (hasId && !(typeof requestId === "string" && requestId.length <= 128 || Number.isSafeInteger(requestId)))) {',
   "new": 'typeof message.method !== "string"\n    || (hasId && !(typeof requestId === "string" && requestId.length < 128 || Number.isSafeInteger(requestId)))) {'},
  {"id": "d", "kind": "swapped-version-negotiation",
   "old": 'MCP_SUPPORTED_VERSIONS.includes(params.protocolVersion) ? params.protocolVersion : MCP_VERSION',
   "new": 'MCP_SUPPORTED_VERSIONS.includes(params.protocolVersion) ? MCP_VERSION : params.protocolVersion'},
 ]},
{"id": "M3", "file": "server/mcp-arg-errors.mjs",
 "tests": ["tests/qa5-agent-errors.test.js"],
 "mutants": [
  {"id": "a", "kind": "off-by-one-near-miss",
   "old": 'return bestScore <= Math.max(limit, 0.5) ? best : null;',
   "new": 'return bestScore < Math.max(limit, 0.5) ? best : null;'},
  {"id": "b", "kind": "flipped-edit-cost",
   "old": 'const cost = a[row - 1] === b[col - 1] ? 0 : 1;',
   "new": 'const cost = a[row - 1] !== b[col - 1] ? 0 : 1;'},
  {"id": "c", "kind": "off-by-one-maxlength",
   "old": 'if (schema.maxLength !== undefined && value.length > schema.maxLength) return "too long";',
   "new": 'if (schema.maxLength !== undefined && value.length >= schema.maxLength) return "too long";'},
  {"id": "d", "kind": "flipped-base64-check",
   "old": 'if (value.length % 4 !== 0) return false;',
   "new": 'if (value.length % 4 === 0) return false;'},
 ]},
{"id": "M4", "file": "server/mcp-discovery.mjs",
 "tests": ["tests/mcp-discovery-aliases.test.js", "tests/mcp-tools-reconciliation.test.js"],
 "mutants": [
  {"id": "a", "kind": "flipped-outside-check",
   "old": "!(agent.memberships ?? []).some(member => member.active !== false)",
   "new": "!(agent.memberships ?? []).some(member => member.active === false)"},
  {"id": "b", "kind": "dropped-common-focus",
   "old": "const focusedNames = focus === undefined ? null : new Set([...FOCUS_COMMON_TOOLS, ...MCP_TOOL_FOCUSES[focus]]);",
   "new": "const focusedNames = focus === undefined ? null : new Set([...MCP_TOOL_FOCUSES[focus]]);"},
 ]},
{"id": "M5", "file": "server/mcp-full-profile.mjs",
 "tests": ["tests/mcp-room-messages-paging.test.js", "tests/mcp-calltime-denials.test.js"],
 "mutants": [
  {"id": "a", "kind": "dropped-roomid-check",
   "old": 'if (!args || typeof args !== "object" || Array.isArray(args) || !validId(args.roomId)) return false;',
   "new": 'if (!args || typeof args !== "object" || Array.isArray(args)) return false;'},
  {"id": "b", "kind": "flipped-guest-carveout",
   "old": '    && store.guestInvites.guestTierOf(memberId) === "contributor") return;',
   "new": '    && store.guestInvites.guestTierOf(memberId) !== "contributor") return;'},
  {"id": "c", "kind": "flipped-private-flag",
   "old": "private: Boolean(event.data?.toMemberId),",
   "new": "private: !Boolean(event.data?.toMemberId),"},
  {"id": "d", "kind": "flipped-spend-void",
   "old": "if (outcome?.isError === true) spend.void();",
   "new": "if (outcome?.isError !== true) spend.void();"},
 ]},
{"id": "M6", "file": "server/mcp-hosted-tools.mjs",
 "tests": ["tests/mcp-tools-reconciliation.test.js"],
 "mutants": [
  {"id": "a", "kind": "dropped-required-field",
   "old": '  }, ["roomId", "body"]), false),',
   "new": '  }, ["roomId"]), false),'},
  {"id": "b", "kind": "flipped-readonly-hint",
   "old": '  }, ["roomId", "body"]), false),',
   "new": '  }, ["roomId", "body"]), true),'},
 ]},
{"id": "M7", "file": "server/mcp-identity-mint.mjs",
 "tests": ["tests/mcp-identity-mint.test.js"],
 "mutants": [
  {"id": "a", "kind": "dropped-notification-guard",
   "old": "  if (!hasId) return null; // Notifications never mint.\n",
   "new": ""},
  {"id": "b", "kind": "off-by-one-id-length",
   "old": "typeof requestId === 'string' && requestId.length <= 128",
   "new": "typeof requestId === 'string' && requestId.length < 128"},
 ]},
{"id": "M8", "file": "server/mcp-public-work.mjs",
 "tests": ["tests/public-work-mcp.test.js"],
 "mutants": [
  {"id": "a", "kind": "flipped-auth-gate",
   "old": " if (!secret && !anonymousPublicWorkMcpTools.includes(selected)) return mcpCallError(requestId, { reason: 'auth_required', tool: name });",
   "new": " if (!secret && anonymousPublicWorkMcpTools.includes(selected)) return mcpCallError(requestId, { reason: 'auth_required', tool: name });"},
  {"id": "b", "kind": "off-by-one-id-length",
   "old": "typeof requestId === 'string' && requestId.length <= 128",
   "new": "typeof requestId === 'string' && requestId.length < 128"},
  {"id": "c", "kind": "boundary-lease-zero",
   "old": "const lease = { type: 'number', exclusiveMinimum: 0, maximum: 24 };",
   "new": "const lease = { type: 'number', minimum: 0, maximum: 24 };"},
 ]},
{"id": "M9", "file": "server/mcp-room-profile.mjs",
 "tests": ["tests/mcp-calltime-denials.test.js"],
 "mutants": [
  {"id": "a", "kind": "bearer-case-sensitive",
   "old": 'if (typeof authorization !== "string" || !/^bearer /i.test(authorization)) {',
   "new": 'if (typeof authorization !== "string" || !/^bearer /.test(authorization)) {'},
  {"id": "b", "kind": "off-by-one-signal-cap",
   "old": "signalIds.length <= 50",
   "new": "signalIds.length < 50"},
  {"id": "c", "kind": "off-by-one-secret-min",
   "old": "args.secret.length >= 16 && args.secret.length <= 2000",
   "new": "args.secret.length > 16 && args.secret.length <= 2000"},
  {"id": "d", "kind": "wrong-escrow-status",
   "old": ': code === "not_authorized" ? 403',
   "new": ': code === "not_authorized" ? 401'},
 ]},
{"id": "M10", "file": "server/work-claim-routes.mjs",
 "tests": ["tests/work-claim-sweep.test.js", "tests/work-claims-read.test.js", "tests/work-claim-qa-fixes.test.js"],
 "mutants": [
  {"id": "a", "kind": "boundary-lease-expiry",
   "old": "&& typeof item.leaseExpiresAt === \"string\" && Date.parse(item.leaseExpiresAt) <= nowMs);",
   "new": "&& typeof item.leaseExpiresAt === \"string\" && Date.parse(item.leaseExpiresAt) < nowMs);"},
  {"id": "b", "kind": "dropped-identity-change-check",
   "old": '    if (current.member.id !== auth?.member?.id) reject(403, "access_denied", "The acting identity changed");\n    if (current.kind === "api-key"',
   "new": '    if (current.kind === "api-key"'},
  {"id": "c", "kind": "off-by-one-receipt-limit",
   "old": "if (!Number.isSafeInteger(limit) || limit < 1 || limit > RECEIPTS_MAX_LIMIT) {",
   "new": "if (!Number.isSafeInteger(limit) || limit < 1 || limit >= RECEIPTS_MAX_LIMIT) {"},
  {"id": "d", "kind": "off-by-one-cursor-offset",
   "old": "&& Number.isSafeInteger(parsed.offset) && parsed.offset >= 0) return parsed.offset;",
   "new": "&& Number.isSafeInteger(parsed.offset) && parsed.offset > 0) return parsed.offset;"},
 ]},
{"id": "M11", "file": "server/bounty-escrow-routes.mjs",
 "tests": ["tests/bounty-escrow-routes.test.js"],
 "mutants": [
  {"id": "a", "kind": "flipped-owner-check",
   "old": "return canonicalLane(ownerId) === canonicalLane(memberId);",
   "new": "return canonicalLane(ownerId) !== canonicalLane(memberId);"},
  {"id": "b", "kind": "dropped-sybil-owner-gate",
   "old": '    if (!isRoomOwner(store, roomId, auth))\n      reject(403, "owner_required", "Only the room owner can confirm or dismiss a sybil flag.");\n',
   "new": ""},
  {"id": "c", "kind": "off-by-one-identity-length",
   "old": "id.length > 256",
   "new": "id.length > 255"},
  {"id": "d", "kind": "array-payload-accepted",
   "old": 'if (typeof payload !== "object" || Array.isArray(payload)) invalidInput(reject, "a JSON object");',
   "new": 'if (typeof payload !== "object") invalidInput(reject, "a JSON object");'},
 ]},
{"id": "M12", "file": "server/matchmaking-routes.mjs",
 "tests": ["tests/matchmaking-routes.test.js"],
 "mutants": [
  {"id": "a", "kind": "dropped-courier-gate",
   "old": '      if (!courier) reject(403, "lane_not_registered", "Register a lane before carrying a decision");\n',
   "new": ""},
  {"id": "b", "kind": "inverted-closed-filter",
   "old": "const closed = rows.filter(r => r.open === false).map(r => r.work_id);",
   "new": "const closed = rows.filter(r => r.open !== false).map(r => r.work_id);"},
 ]},
{"id": "M13", "file": "server/inbox-collab-routes.mjs",
 "tests": ["tests/inbox-collab-http.test.js"],
 "mutants": [
  {"id": "a", "kind": "flipped-human-gate",
   "old": 'if (caller.kind !== "human") reject(403, "human_required",',
   "new": 'if (caller.kind === "human") reject(403, "human_required",'},
  {"id": "b", "kind": "flipped-agent-gate",
   "old": 'if (caller.kind !== "agent") reject(403, "agent_required", "This action requires an agent identity.");',
   "new": 'if (caller.kind === "agent") reject(403, "agent_required", "This action requires an agent identity.");'},
  {"id": "c", "kind": "flipped-routing-policy-gate",
   "old": "if (caller.id !== ownerId && callerAgentId !== fields.agentId) {",
   "new": "if (caller.id !== ownerId || callerAgentId !== fields.agentId) {"},
  {"id": "d", "kind": "head-falls-in-transaction",
   "old": 'if (["GET", "HEAD"].includes(req.method)) return handleInboxCollabCore(options);',
   "new": 'if (["GET"].includes(req.method)) return handleInboxCollabCore(options);'},
 ]},
{"id": "M14", "file": "server/agent-plugin-routes.mjs",
 "tests": ["tests/developer-contract.test.js", "tests/open-routes.test.js"],
 "mutants": [
  {"id": "a", "kind": "dropped-key-mgmt-gate",
   "old": '    if (auth.keyId !== null) reject(403, "insufficient_scope", "API keys cannot manage API keys; use the identity secret");\n',
   "new": ""},
  {"id": "b", "kind": "wildcard-grants-all",
   "old": "export const grantsScope = (scopes, required) => (scopes ?? []).some(scope =>\n  scope === required || (scope.endsWith(\":*\") && required.startsWith(scope.slice(0, -1))));",
   "new": "export const grantsScope = (scopes, required) => (scopes ?? []).some(scope =>\n  scope === required || scope.endsWith(\":*\"));"},
 ]},
{"id": "M15", "file": "server/operator-routes.mjs",
 "tests": ["tests/operator-purge.test.js"],
 "mutants": [
  {"id": "a", "kind": "dropped-operator-token-check",
   "old": '    if (!operatorTokenMatches(token)) reject(404, "not_found", "Not found");\n',
   "new": ""},
 ],
},
{"id": "M15b", "file": "server/legal-routes.mjs",
 "tests": ["tests/legal-pages.test.js"],
 "mutants": [
  {"id": "a", "kind": "dropped-pow-check",
   "old": "if (!REPORT_FIELDS.every(key => Object.hasOwn(data, key)) || !verifyReportProof(data, store.now())) {",
   "new": "if (!REPORT_FIELDS.every(key => Object.hasOwn(data, key))) {"},
 ]},
{"id": "M15c", "file": "server/supervision-routes.mjs",
 "tests": ["tests/supervision-routes.test.js"],
 "mutants": [
  {"id": "a", "kind": "flipped-confirm-gate",
   "old": "if (data?.confirm !== true) {",
   "new": "if (data?.confirm === true) {"},
  {"id": "b", "kind": "off-by-one-suggestion-index",
   "old": "if (!Number.isInteger(index) || index < 1 || index > suggestions.length) {",
   "new": "if (!Number.isInteger(index) || index < 0 || index > suggestions.length) {"},
 ]},
{"id": "M15d", "file": "server/next-actions-routes.mjs",
 "tests": ["tests/next-actions.test.js"],
 "mutants": [
  {"id": "a", "kind": "dropped-auth-gate",
   "old": '    if (!selected.token) reject(401, "unauthenticated", "Authenticate: Authorization: Bearer <identitySecret>");\n',
   "new": ""},
 ]},
]}
